kind: pipeline
type: docker
name: maven
steps:
- name: test
  image: ramalingam81/centos6-java8
  commands:
  - ls
  - mvn -v
  - mvn install
###  - mvn package -Dmaven.test.skip=true -U
#  - mvn dockerfile:build
#  - mvn dockerfile:push 
