kind: pipeline
type: docker
name: maven
steps:
- name: test
  image: ramalingam81/maven-apt:latest
  commands:
  - ls
  - mvn -v
  - mvn install

- name: test2
  image: ramalingam81/maven-apt:latest
  commands:
  - ls
  - mvn -v
  - mvn install
- name: test3
  image: ramalingam81/maven-apt:latest
  commands:
  - ls
  - mvn -v
  - mvn install

- name: test4
  image: ramalingam81/maven-apt:latest
  commands:
  - ls
  - mvn -v
  - mvn install
# to push docker image into ecrrepo
# to push docker image into ecrrepo
- name: publish
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    region: us-east-1
    tags:
      - latest
      - ${DRONE_BUILD_NUMBER}
    repo: 633025986259.dkr.ecr.us-east-1.amazonaws.com/maven
    registry: 633025986259.dkr.ecr.us-east-1.amazonaws.com
  when:
    event: push
