kind: pipeline
type: docker
name: maven
steps:
- name: test
  image: ramalingam81/maven-apt:latest
  commands:
  - ls
  - mvn -v
    #  - mvn install
  - mvn install -Dmaven.test.skip=true -U
#  - mvn package -Dmaven.test.skip=true -U
#  - mvn dockerfile:build
#  - mvn dockerfile:push 
