name: Veracode Static Analysis Demo
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        
      #- name: Build with Maven # Compiling the .war binary from the checked out repo source code to upload to the scanner in the next step
      #  run: mvn -B package --file app/pom.xml
      
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        run: ls & pwd
        with:
          appname: 'VeraDemo Actions'
          createprofile: false
          filepath: '/home/runner/work/test-docker/test-docker/target/test-docker-0.0.1-SNAPSHOT.jar'
          vid: '${{ secrets.VERACODE_ID }}'
          vkey: '${{ secrets.VERACODE_KEY }}'
